name: Secret Scanning

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    name: Gitleaks
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  truffleHog:
    runs-on: ubuntu-latest
    name: TruffleHog
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug

  detect-secrets:
    runs-on: ubuntu-latest
    name: Detect Secrets
    steps:
      - uses: actions/checkout@v4

      - name: Run Detect Secrets
        uses: reviewdog/action-detect-secrets@v0.28.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_level: error
