# Funding options for The Lost Yeti Kitchen & Bar project

# GitHub Sponsors
github: # [yourusername]

# Open Collective
open_collective: # lost-yeti

# Ko-fi
ko_fi: # lostyeti

# Patreon
patreon: # lostyeti

# Buy Me a Coffee
custom: # ['https://www.buymeacoffee.com/lostyeti']
